version: 0.2
phases:
  pre_build:
    commands:
      - echo logging...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 010438472482.dkr.ecr.ap-southeast-1.amazonaws.com
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app-jjb .
      - docker tag my-app-jjb:latest 010438472482.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-jjb:latest

      
  post_build:
    commands:
      - echo Build completed
      - echo pushing into ECR
      - docker push 010438472482.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-jjb:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "my-app" "010438472482.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-jjb:latest" > imagedefinitions.json
      
artifacts:
  files: 
   - imagedefinitions.json
