AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ECS cluster with a Fargate service

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID for ECS Fargate

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnets in the above VPC

  ECRImageUri:
    Type: String
    Description: The URI of the Docker image in ECR

  ContainerPort:
    Type: Number
    Default: 80
    Description: The port on which the container will listen

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies: 
        - PolicyName: TaskExecutionPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                Resource: "*"

  FargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-app-task
      Cpu: 256
      Memory: 512
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: my-app-container
          Image: !Ref ECRImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/my-app
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref FargateTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ECSSecurityGroup.GroupId
          Subnets: !Ref SubnetIds

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref ECSCluster

  ServiceName:
    Description: Name of the ECS service
    Value: !Ref ECSService
